### ISSUE TITLE
This addon is an unfolding PR disaster for Firefox

### ISSUE THREAD

**Issue by jimrandomh** [mozilla/addon-wr#46]
You appear to have accidentally gone live on a large fraction of Firefox installs which didn't opt into anything, and the addon metadata makes it look like malware. A lot of people are *pissed*. Furthermore, no one involved with this project or with Mozilla seems to be doing PR damage control, or showing any awareness of what's happening.

https://news.ycombinator.com/item?id=15931730
https://www.reddit.com/r/firefox/comments/7jh9rv/what_is_looking_glass/

**Comment by SimHacker** [comment]
Also, please stop claiming it's an "Augmented Reality Game": it absolutely is not that. 

The case for "Alternative Reality Game" is pretty thin too, since there's no "intense player involvement with a story that takes place in real time and evolves according to players' responses". 

It's just a "Alternative TV Show Advertisement". Transparency, please.

https://en.wikipedia.org/wiki/Alternate_reality_game

https://news.ycombinator.com/item?id=15956601

**Comment by Daniel15** [comment]
Looks like Mozilla have posted an official response: https://blog.mozilla.org/firefox/update-looking-glass-add/
